<?php return array (
  'site_title' => 'Influencer',
  'theme' => 'basic',
  'primaryColor' => '#f05822',
  'secondaryColor' => '#f0aa22',
  'time_zone' => 'Asia/Dhaka',
  'default_file_driver' => 'local',
  'base_currency' => 'USD',
  'currency_symbol' => '$',
  'fraction_number' => 2,
  'paginate' => 15,
  'sender_email' => 'support@mail.com',
  'sender_email_name' => 'Binary Operation',
  'email_configuration' => 
  array (
    'name' => 'smtp',
    'smtp_host' => 'smtp.mailtrap.io',
    'smtp_port' => '2525',
    'smtp_encryption' => 'tls',
    'smtp_username' => '5d3da681936594',
    'smtp_password' => 'd744c7e208c964',
  ),
  'push_notification' => 1,
  'email_notification' => 1,
  'email_verification' => 0,
  'sms_notification' => 1,
  'sms_verification' => 0,
  'tawk_id' => '5a929d64d7591465c707fe43',
  'tawk_status' => 0,
  'fb_messenger_status' => 0,
  'fb_app_id' => '1983831301869331',
  'fb_page_id' => '1983831301869331',
  'reCaptcha_status_login' => 0,
  'reCaptcha_status_registration' => 0,
  'MEASUREMENT_ID' => 'G-TFQZ8YZ468',
  'analytic_status' => 0,
  'error_log' => 1,
  'strong_password' => 0,
  'registration' => 0,
  'is_active_cron_notification' => 0,
  'logo_image' => 'logo/logo.png',
  'footer_image' => 'logo/footer-logo.png',
  'favicon_image' => 'logo/favicon.png',
  'admin_logo' => 'logo/admin-logo.png',
  'logo_meta' => 'logo/meta.png',
  'daily_limit' => 5,
  'days' => 3,
);