<?php
$arr = [
	"Pay Now",
    "Useful Links",
	"Reports Summary",
	"Transaction List",
	"Balance",
	"Listing Order Lists",
	"Order Lists",
	"Transaction ID",
	"Amount",
	"Time extend",
	"Type",
	"Package",
	"Created Time",
	"Dashboard",
	"Profile",
	"Jobs List",
	"Send Payout Request",
	"Send Offers",
	"Testimonial request awaiting for response",
	"Job Invitation",
	"Hire Freelancer",
	"Listing Orders",
	"Payout Request",
	"Transactions",
	"Messages",
	"Support Ticket",
	"Reports",
	"HOME",
	"INFLUENCERS",
	"Influencer Listings",
	"LISTINGS",
	"JOBS",
	"BLOG",
	"CONTACT",
	"Userful Links",
	"Terms & Conditions",
	"Privacy Policy",
	"Faq",
	"Contact Us",
	"Talented Influencers",
	"Contact",
	"Influencers",
	"Follow Us On",
	"Recent Jobs",
	"Best Matches",
	"Save Jobs",
	"Member since",
	"Advanced Search",
	"Jobs",
	"Experience Level",
	"Expert",
	"Number of revision",
	"1 time revision",
	"2 time revision",
	"3 time revision",
	"Unlimited revision",
	"Intermidiate",
	"Which industry are you in? (Optional)",
	"Frequently Asked Questios ",
	"Requirements for Client ",
	"Edit Listings",
	"Tell us a bit about yourself(Optional) ",
	"Tell us a bit about yourself(Optional) ",
	"Explain Your Listing in Brief *",
	"Expand submission date time",
	"No portfolio information available",
	" Total Orders",
	"Endorsements from past clients",
	"No employment history available",
	"Showcasing client testimonials can strengthen your profile.",
	"Entry",
	"Expired",
	"Job Type",
	"Hourly",
	"Project",
	"Proposal",
	"Hire Freelancer",
	"Freelancer",
	"From",
	"Title",
	"SL",
	"Deadline",
	"Order",
	"Member Since",
	"Total Orders",
	"Description",
	"Social Links",
	"Skills",
	"Testimonial",
	"Employment History",
	"Portfolio",
	"Education",
	"Certifications",
	"No Data Found",
	"Known Languages",
	"Date",
	"READ MORE",
	"Subscribe Newsletter",
	"Startin At",
	"Sell",
	"Quick Links",
	"UserFul Links",
	"Get In Touch With Us",
	"Create Listings",
	"Listings",
	"Fund Lists",
	"Delivery",
	"Revision's",
	"Price",
	" Select Category ",
	"Select a Sub Category",
	"Category",
	"Sub Category",
	"Total Sell",
	" Extra Services ",
	" Frequently Asked Questions",
	"Other open jobs by this Client",
	"Note",
	"Activity on this job",
	"Attachment",
	"Skills and Expertise",
	"Need to know",
	"Job Details",
	"About the client",
	"Job Link",
	"Proposals",
	"Scope",
	"CONTACT ME",
	"Hired",
	"Reviews",
	"Related Tags",
	"Recommend For You",
	"What's Included",
	"Edit Certification",
	"Add New Certification",
	"Edit Employment",
	"Add Education",
	"No work history available",
	"Start your search",
	"No information available",
	"Drag or upload project files",
	"Ex. I’m an Italian restaurant owner and I want to expand my business.",
	"Listing your certifications can help prove your specific knowledge or abilities. (+10%) You can add them manually.",
	"You have done 72% more sales today. Check your new badge in your profile.",
	"If enable transaction charge will deduct from receiver",
	"Preview Deposit",
	"Home",
	"Gateway",
	"Name",
	"Charge",
	"Package",
	"Confirm",
	"Deposit",
	"Time Extend",
	"Currency",
	"Payable amount	",
	"Receive Invitation",
	"Details",
	"Select Payment Method",
	"Sent/Received Money",
	"Search",
	"Sender",
	"Hiring Freelencer Lists",
	"Freelancer Lists",
	"Receiver",
	"No Data available",
	"Receiver E-Mail",
	"Transaction ID",
	"Status",
	"Sent",
	"Received",
	"Success",
	"Pending",
	"No data found",
	"E-mail",
	"Min Amount",
	"Maximum Amount",
	"Transaction Date",
	"Select Currency",
	"All Type",
	"CREATE JOB",
	"Listing Lists",
	"Milestone",

	"Action",
	"Escrow",
	"Open",
	"MESSAGES",
	"Solved",
	"Close",
	"View",
	"All Status",
	"You are muted",
	"Type Here",
	"You are muted",
	"Upload File",
	"File",
	"Issue has been solved by",
	"Issue has been closed by",
	"have been muted by",
	"have been unmuted by",
	"Preview Escrow",
	"Request Amount",
	"Percentage Charge",
	"Fixed Charge",
	"Total Charge",
	"Receivable Amount",
	"Note",
	"Security Pin",
	"Please enter your security PIN",
	"Escrow Request",
	"Recipient email or username",
	"Create escrow request",
	"Available Balance",
	"Min Request Limit",
	"Max Request Limit",
	"Escrow lists",
	"Generated",
	"No File",
	"Deposited",
	"Request for payment",
	"Payment Disbursed",
	"Canceled",
	"Hold",
	"Dispute",
	"N/A",
	"Refunded",
	"Escrow payment",
	"Percentage charge",
	"Fixed charge",
	"Total charge",
	"View Dispute Details",
	"Payment disbursed",
	"Request Payment",
	"View Proposal",
	"Invitation",
	"Welcome",
	"Empty Details",
	"Accept",
	"Cancel",
	"Confirmation",
	"Are you sure you want to",
	"Confirmed",
	"Exchange",
	"Confirm Exchange",
	"Exchange Rate",
	"You will get",
	"From Wallet",
	"To Wallet",
	"Transaction Details",
	"Exchange rate",
	"Remaining Balance",
	"Updated Balance",
	"Select To Currency",
	"Exchange Amount",
	"Completed",
	"Min Deposit Limit",
	"Max Deposit Limit",
	"New Balance",
	"Payable Amount",
	"Transfer Charge",
	"Method",
	"Add Fund",
	"All Currency",
	"developed by",
	"Ohh No",
	"Are you sure you want to logout",
	"Logout",
	"Dashboard",
	"Features",
	"Fund added List",
	"Send Money",
	"Transfer List",
	"Pending List",
	"Request Money",
	"New Request",
	"All Request",
	"All Exchange",
	"Pending list",
	"Redeem",
	"Generate New Code",
	"Generated List",
	"Insert Redeem Code",
	"Create a request",
	"Escrow List",
	"Voucher",
	"Create voucher",
	"Voucher List",
	"Payout",
	"Request Payout",
	"Payout List",
	"Transactions",
	"Tickets",
	"Settings Panel",
	"Two Factor",
	"Manage PIN uses",
	"Alerts Center",
	"Clear all",
	"No notification found",
	"Change Password",
	"Profile",
	"INFLUENCERS",
	"No Listing Data",
	"Pay with",
	"Your Card Information",
	"Enter your card number",
	"Enter the name on your card",
	"Submit",
	"Payment Preview",
	"PLEASE SEND EXACTLY",
	"TO",
	"SCAN TO SEND",
	"Pay Now",
	"Pay via Monnify",
	"Pay with PAYPAL",
	"Stripe Payment",
	"Pay with VoguePay",
	"Choose File",
	"Payout Method",
	"Charge Amount",
	"Total Payable",
	"Request user",
	"Paid by",
	"Payment Done",
	"Payout method list",
	"Choose a payout method",
	"Back",
	"Enter Amount",
	"Withdraw",
	"Min limit",
	"Max limit",
	"Your full name",
	"City",
	"Enter your city",
	"Phone",
	"Enter your phone number",
	"State",
	"Enter your state",
	"Address",
	"Enter your address",
	"Choose profile picture",
	"Update Profile",
	"Current balance",
	"Generate redeem",
	"Receiver will received",
	"Charge deduct from",
	"Redeem Generate",
	"Generate redeem code",
	"Receiver will pay the txn charge",
	"Generate",
	"Redeem code",
	"Redeem cods",
	"Unused",
	"Used",
	"Redeem Code",
	"Submit redeem code",
	"Redeem codes",
	"Confirm Transfer",
	"Transfer limit",
	"Yes",
	"Are you sure you want to cancel",
	"New Ticket",
	"Subject",
	"Message",
	"Job Offer",
	"Choose files",
	"Submit Ticket",
	"Tickets Log",
	"Last Reply",
	"Answered",
	"Replied",
	"Closed",
	"No Data Found",
	"Duration",
	"Ticket",
	"Customer Replied",
	"File(s)",
	"Are you want to close ticket",
	"Receiver name",
	"Create Security pin",
	"Security Question",
	"Answer",
	"Security question answer",
	"Hints",
	"In future helps you guess the answer",
	"Security pin confirmation",
	"Create security PIN",
	"Manage pin uses",
	"Save Changes",
	"Reset security pin",
	"Old security pin",
 	"eg:1234",
	"Confirm pin",
	"Reset security PIN",
	"Preview Voucher Request",
	"Voucher Create",
	"Recipient email",
	"or username",
	"Please enter valid email",
	"Voucher lists",
	"Payment done",
	"Sender request to payment disburse",
	"Min Payment Limit",
	"Max Payment Limit",
	"Voucher payment",
	"Requester Name",
	"Confirm Payment",
	"Cancel Payment",
	"Payment Failed",
	"Sorry",
	"We really appreciate you giving us a moment of your time today but unfortunately the payment was unsuccessful due to",
	"it seems some issue in server to server communication. Kindly connect with administrator",
	"Go back to Home",
	"Copyright",
	"All Rights Reserved",
	"You are logged in",
	"Payment Success",
	"THANK YOU",
	"Thanks a bunch for filling that out. It means a lotto us, just like you do! We really appreciate you giving us a moment of your time today. Thanks for being with us.",
	"Current password",
	"Enter your current password",
	"Password",
	"Enter new password",
	"Repeat password",
	"Confirm Password",
	"Please confirm your password before continuing",
	"Forgot Your Password",
	"User | Reset Password",
	"Reset Password",
	"Enter Email",
	"Send Password Reset Link",
	"Create an Account",
	"Already have an account",
	"Login",
	"Sign In",
	"Sign In To Your Account",
	"Username Or Email Address",
	"Remember Me",
	"Don\\'t have an account",
	"Sing up",
	"Create Your Account",
	"Enter Full Name",
	"Enter Email Address",
	"Enter Username",
	"Repeat Password",
	"Create Account",
	"Sing in",
	"User | Verify E-Mail",
	"Verify Your Email Address",
	"A fresh verification link has been sent to your email address.",
	"Before proceeding, please check your email for a verification link. If you did not receive the email.",
	"click here to request another",
	"Subscribe",
	"PRIVACY & TOS",
	"Advertiser Agreement",
	"Acceptable policy",
	"Privacy Policy",
	"Technology privacy",
	"Developer Agreement",
	"Quick Links",
	"About",
	"Our Performance",
	"Help",
	"FAQ",
	"Blog",
	"Blogs",
	"JOBS",
	"Bid Rate",
	"About Us",
	"Read More",
	"Happy Clients",
	"Weekly Transaction",
	"Monthly Transaction",
	"Yearly Transaction",
	"Blog Details",
	"Popular Posts",
	"Send Message",
	"Download On",
	"Earnings",
	"Total Job Proposal",
	"Avg. selling price",
	"App Store",
	"Job is closed",
	"Google Play",
	"Logo Update",
	"Short Descriptions",
	"add-fund-short-description",
	"deposit-short-description",
	"payout-short-description",
	"redeem-code-short-description",
	"request-money-short-description",
	"send-money-short-description",
	"voucher-payment-short-description",
	"escrow-short-description",
	"exchange-money-short-description",
	"If enable transaction charge will deduct from receiver",
];
return $arr;
